AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role for AWS Load Balancer Controller using IRSA

Parameters:
  ClusterStackName:
    Type: String
    Default: video-analytics-cluster
    Description: Name of the EKS cluster CloudFormation stack

  ClusterName:
    Type: String
    Default: video-analytics-cluster
    Description: Name of the EKS cluster

Resources:
  AWSLoadBalancerControllerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClusterName}-alb-controller-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                Fn::ImportValue: !Sub '${ClusterStackName}-OIDCProviderArn'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                Fn::Sub:
                  - '${OIDCProvider}:sub'
                  - OIDCProvider:
                      Fn::Select:
                        - 1
                        - Fn::Split:
                            - 'oidc-provider/'
                            - Fn::ImportValue: !Sub '${ClusterStackName}-OIDCProviderArn'
                system:serviceaccount:kube-system:aws-load-balancer-controller
              StringEquals:
                Fn::Sub:
                  - '${OIDCProvider}:aud'
                  - OIDCProvider:
                      Fn::Select:
                        - 1
                        - Fn::Split:
                            - 'oidc-provider/'
                            - Fn::ImportValue: !Sub '${ClusterStackName}-OIDCProviderArn'
                sts.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::699013266147:policy/AWSLoadBalancerControllerIAMPolicy

Outputs:
  ServiceAccountRoleArn:
    Description: IAM Role ARN for AWS Load Balancer Controller Service Account
    Value: !GetAtt AWSLoadBalancerControllerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ALBControllerRoleArn'
