AWSTemplateFormatVersion: '2010-09-09'
Description: Video Analytics - EKS Cluster with Managed Node Group (imports network from eks-network stack)

Parameters:
  NetworkStackName:
    Type: String
    Default: video-analytics-network
    Description: Name of the network CloudFormation stack to import VPC/subnet values from

  ClusterName:
    Type: String
    Default: video-analytics-cluster
    Description: Name for the EKS cluster

  KubernetesVersion:
    Type: String
    Default: '1.30'
    AllowedValues:
      - '1.30'
      - '1.29'
    Description: Kubernetes version for EKS cluster

  NodeInstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
    Description: EC2 instance type for worker nodes

  NodeDesiredSize:
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
    Description: Desired number of worker nodes

  NodeMinSize:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    Description: Minimum number of worker nodes

  NodeMaxSize:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 20
    Description: Maximum number of worker nodes

Resources:
  # ==================== IAM ROLES ====================
  
  # EKS Cluster IAM Role
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClusterName}-cluster-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-cluster-role'

  # EKS Node IAM Role
  NodeInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ClusterName}-node-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-node-role'

  # Additional IAM Policy for ECR and CloudWatch
  NodeAdditionalPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ClusterName}-node-additional-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Resource: '*'
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/eks/${ClusterName}/*'
      Roles:
        - !Ref NodeInstanceRole

  # IAM Policy for Cluster Autoscaler
  ClusterAutoscalerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ClusterName}-autoscaler-policy'
      Roles:
        - !Ref NodeInstanceRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeScalingActivities
              - autoscaling:DescribeTags
              - ec2:DescribeInstanceTypes
              - ec2:DescribeLaunchTemplateVersions
            Resource: '*'
          - Effect: Allow
            Action:
              - autoscaling:SetDesiredCapacity
              - autoscaling:TerminateInstanceInAutoScalingGroup
            Resource: '*'
            Condition:
              StringEquals:
                autoscaling:ResourceTag/k8s.io/cluster-autoscaler/enabled: 'true'
                autoscaling:ResourceTag/k8s.io/cluster-autoscaler/${ClusterName}: 'owned'

  # IAM Role for AWS Load Balancer Controller Service Account
  AWSLoadBalancerControllerRole:
    Type: AWS::IAM::Role
    DependsOn: EKSCluster
    Properties:
      RoleName: !Sub '${ClusterName}-alb-controller-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !GetAtt EKSClusterOIDCProvider.Arn
            Action: sts:AssumeRoleWithWebIdentity
      Policies:
        - PolicyName: AWSLoadBalancerControllerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                Resource: '*'
                Condition:
                  StringEquals:
                    iam:AWSServiceName: elasticloadbalancing.amazonaws.com
              - Effect: Allow
                Action:
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeAddresses
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeInternetGateways
                  - ec2:DescribeVpcs
                  - ec2:DescribeVpcPeeringConnections
                  - ec2:DescribeSubnets
                  - ec2:DescribeSecurityGroups
                  - ec2:DescribeInstances
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DescribeTags
                  - ec2:GetCoipPoolUsage
                  - ec2:DescribeCoipPools
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeListeners
                  - elasticloadbalancing:DescribeListenerCertificates
                  - elasticloadbalancing:DescribeSSLPolicies
                  - elasticloadbalancing:DescribeRules
                  - elasticloadbalancing:DescribeTargetGroups
                  - elasticloadbalancing:DescribeTargetGroupAttributes
                  - elasticloadbalancing:DescribeTargetHealth
                  - elasticloadbalancing:DescribeTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - cognito-idp:DescribeUserPoolClient
                  - acm:ListCertificates
                  - acm:DescribeCertificate
                  - iam:ListServerCertificates
                  - iam:GetServerCertificate
                  - waf-regional:GetWebACL
                  - waf-regional:GetWebACLForResource
                  - waf-regional:AssociateWebACL
                  - waf-regional:DisassociateWebACL
                  - wafv2:GetWebACL
                  - wafv2:GetWebACLForResource
                  - wafv2:AssociateWebACL
                  - wafv2:DisassociateWebACL
                  - shield:GetSubscriptionState
                  - shield:DescribeProtection
                  - shield:CreateProtection
                  - shield:DeleteProtection
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateSecurityGroup
                Resource: '*'
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                Resource: arn:aws:ec2:*:*:security-group/*
                Condition:
                  StringEquals:
                    ec2:CreateAction: CreateSecurityGroup
                  'Null':
                    aws:RequestTag/elbv2.k8s.aws/cluster: 'false'
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DeleteTags
                Resource: arn:aws:ec2:*:*:security-group/*
                Condition:
                  'Null':
                    aws:RequestTag/elbv2.k8s.aws/cluster: 'true'
                    aws:ResourceTag/elbv2.k8s.aws/cluster: 'false'
              - Effect: Allow
                Action:
                  - ec2:AuthorizeSecurityGroupIngress
                  - ec2:RevokeSecurityGroupIngress
                  - ec2:DeleteSecurityGroup
                Resource: '*'
                Condition:
                  'Null':
                    aws:ResourceTag/elbv2.k8s.aws/cluster: 'false'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateLoadBalancer
                  - elasticloadbalancing:CreateTargetGroup
                Resource: '*'
                Condition:
                  'Null':
                    aws:RequestTag/elbv2.k8s.aws/cluster: 'false'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:CreateListener
                  - elasticloadbalancing:DeleteListener
                  - elasticloadbalancing:CreateRule
                  - elasticloadbalancing:DeleteRule
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:AddListenerCertificates
                  - elasticloadbalancing:RemoveListenerCertificates
                  - elasticloadbalancing:ModifyListener
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:AddTags
                  - elasticloadbalancing:RemoveTags
                Resource: '*'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - elasticloadbalancing:SetIpAddressType
                  - elasticloadbalancing:SetSecurityGroups
                  - elasticloadbalancing:SetSubnets
                  - elasticloadbalancing:DeleteLoadBalancer
                  - elasticloadbalancing:ModifyTargetGroup
                  - elasticloadbalancing:ModifyTargetGroupAttributes
                  - elasticloadbalancing:DeleteTargetGroup
                Resource: '*'
                Condition:
                  'Null':
                    aws:ResourceTag/elbv2.k8s.aws/cluster: 'false'
              - Effect: Allow
                Action:
                  - elasticloadbalancing:RegisterTargets
                  - elasticloadbalancing:DeregisterTargets
                Resource: arn:aws:elasticloadbalancing:*:*:targetgroup/*/*
              - Effect: Allow
                Action:
                  - elasticloadbalancing:SetWebAcl
                  - elasticloadbalancing:ModifyListener
                  - elasticloadbalancing:AddListenerCertificates
                  - elasticloadbalancing:RemoveListenerCertificates
                  - elasticloadbalancing:ModifyRule
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-alb-controller-role'

  # ==================== EKS CLUSTER ====================
  
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub '${NetworkStackName}-EKSClusterSecurityGroupId'
        SubnetIds:
          - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet1Id'
          - Fn::ImportValue: !Sub '${NetworkStackName}-PublicSubnet2Id'
          - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
          - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet2Id'
        EndpointPublicAccess: true
        EndpointPrivateAccess: true
        PublicAccessCidrs:
          - 0.0.0.0/0
      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler
      Tags:
        - Key: Name
          Value: !Ref ClusterName
        - Key: Environment
          Value: Production

  # ==================== EKS NODE GROUP ====================
  
  NodeGroup:
    Type: AWS::EKS::Nodegroup
    DependsOn: 
      - EKSCluster
      - NodeAdditionalPolicy
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Sub '${ClusterName}-node-group'
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet2Id'
      ScalingConfig:
        DesiredSize: !Ref NodeDesiredSize
        MinSize: !Ref NodeMinSize
        MaxSize: !Ref NodeMaxSize
      InstanceTypes:
        - !Ref NodeInstanceType
      AmiType: AL2_x86_64
      DiskSize: 20
      CapacityType: ON_DEMAND
      UpdateConfig:
        MaxUnavailable: 1
      Labels:
        role: frontend
        environment: production
        workload: video-analytics
      Tags:
        Name: !Sub '${ClusterName}-node'
        Environment: Production
        k8s.io/cluster-autoscaler/enabled: 'true'
        k8s.io/cluster-autoscaler/video-analytics-cluster: 'owned'

  # Second Node Group - For system/backend workloads
  NodeGroupSystem:
    Type: AWS::EKS::Nodegroup
    DependsOn: 
      - EKSCluster
      - NodeAdditionalPolicy
    Properties:
      ClusterName: !Ref ClusterName
      NodegroupName: !Sub '${ClusterName}-system-node-group'
      NodeRole: !GetAtt NodeInstanceRole.Arn
      Subnets:
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet1Id'
        - Fn::ImportValue: !Sub '${NetworkStackName}-PrivateSubnet2Id'
      ScalingConfig:
        DesiredSize: 1
        MinSize: 1
        MaxSize: 3
      InstanceTypes:
        - t3.small
      AmiType: AL2_x86_64
      DiskSize: 20
      CapacityType: ON_DEMAND
      UpdateConfig:
        MaxUnavailable: 1
      Labels:
        role: system
        environment: production
        workload: monitoring
      Tags:
        Name: !Sub '${ClusterName}-system-node'
        Environment: Production
        k8s.io/cluster-autoscaler/enabled: 'true'
        k8s.io/cluster-autoscaler/video-analytics-cluster: 'owned'

  # ==================== OIDC PROVIDER (for IRSA - IAM Roles for Service Accounts) ====================
  
  EKSClusterOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: !GetAtt EKSCluster.OpenIdConnectIssuerUrl
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 9e99a48a9960b14926bb7f3b02e22da2b0ab7280

# ==================== OUTPUTS ====================
Outputs:
  ClusterName:
    Description: EKS Cluster Name
    Value: !Ref EKSCluster
    Export:
      Name: !Sub '${AWS::StackName}-ClusterName'

  ClusterArn:
    Description: EKS Cluster ARN
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'

  ClusterEndpoint:
    Description: EKS Cluster API Endpoint
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: !Sub '${AWS::StackName}-ClusterEndpoint'

  ClusterSecurityGroupId:
    Description: Security Group ID attached to EKS Cluster
    Value:
      Fn::ImportValue: !Sub '${NetworkStackName}-EKSClusterSecurityGroupId'
    Export:
      Name: !Sub '${AWS::StackName}-ClusterSecurityGroup'

  NodeGroupName:
    Description: EKS Node Group Name (Frontend)
    Value: !Ref NodeGroup
    Export:
      Name: !Sub '${AWS::StackName}-NodeGroupName'

  NodeGroupSystemName:
    Description: EKS System Node Group Name
    Value: !Ref NodeGroupSystem
    Export:
      Name: !Sub '${AWS::StackName}-NodeGroupSystemName'

  NodeInstanceRoleArn:
    Description: IAM Role ARN for EKS Worker Nodes
    Value: !GetAtt NodeInstanceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-NodeRoleArn'

  OIDCProviderArn:
    Description: OIDC Provider ARN for IRSA (IAM Roles for Service Accounts)
    Value: !GetAtt EKSClusterOIDCProvider.Arn
    Export:
      Name: !Sub '${AWS::StackName}-OIDCProviderArn'

  KubeconfigCommand:
    Description: Command to update kubeconfig for kubectl access
    Value: !Sub 'aws eks update-kubeconfig --region ${AWS::Region} --name ${ClusterName}'

  AWSLoadBalancerControllerRoleArn:
    Description: IAM Role ARN for AWS Load Balancer Controller (use with service account)
    Value: !GetAtt AWSLoadBalancerControllerRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ALBControllerRoleArn'
